name: Package to Nuget

on:
  push:
    branches: [ pack ]
 # 支持手动打包
  workflow_dispatch:

jobs:
  
  pack:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      # 
      - name: Run Pack
        run: dotnet pack src/BulmaRazor/BulmaRazor.csproj -c Release -o package 
        
      - name: Publish nuget
        env: 
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: dotnet nuget push package/BulmaRazor.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
